feat: deleted prefer-await-to-then
typedigital/eslint-config-typedigital pull request #85
Opened 2022-04-06 07:07 UTC by bob606

Deleted typescript-prefer-await as it is too opinionated about where to use await.

2022-04-16 13:53 UTC, timidak requested changes
Just a few changes 🙂

2022-04-16 13:53 UTC, timidak commented on base.js
> -    'promise/prefer-await-to-then': 'warn', // https://github.com/xjamundx/eslint-plugin-promise/blob/master/docs/rules/prefer-await-to-then.md
I would remove the comment, too.

2022-04-16 13:53 UTC, timidak commented on base.js
>      // * it's better to use one syntax so the await syntax should be our standard
```suggestion
    // * it's better to use one syntax so the await syntax should be our standard and in some cases the `then` syntax can be used
```

2022-04-16 13:53 UTC, timidak commented on base.js
> -    'promise/prefer-await-to-then': 'warn', // https://github.com/xjamundx/eslint-plugin-promise/blob/master/docs/rules/prefer-await-to-then.md
Also I would leave the rule in the file and just turn it `"off"`. If we change our mind later, we do not have to search for the rule in the docs. What do you mean?

2022-04-20 05:40 UTC, bob606 commented
please merge if you approve the changes @timidak

2022-04-21 15:03 UTC, timidak approved these changes
👍🏼 nice one!

2022-04-21 15:03 UTC, merged